name: Blog Post
description: Create a new blog post
title: "[Blog] "
labels: ["blog"]
body:
  - type: input
    id: slug
    attributes:
      label: Slug
      description: URL friendly name (e.g. my-new-post)
      placeholder: my-new-post
    validations:
      required: true
  - type: dropdown
    id: lang
    attributes:
      label: Language
      options:
        - zh
        - en
        - ja
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short summary for SEO and previews
    validations:
      required: false
  - type: textarea
    id: coverImage
    attributes:
      label: Cover Image
      description: URL or Markdown image (e.g. ![alt](url)). You can paste an image here to get a URL.
    validations:
      required: false
  - type: textarea
    id: body
    attributes:
      label: Content
      description: Write your post content here (Markdown)
    validations:
      required: true
